-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.academic_term
(
    term_id bigserial NOT NULL,
    school_year character varying(9) COLLATE pg_catalog."default" NOT NULL,
    semester character varying(20) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT false,
    CONSTRAINT academic_term_pkey PRIMARY KEY (term_id),
    CONSTRAINT academic_term_school_year_semester_key UNIQUE (school_year, semester)
);

CREATE TABLE IF NOT EXISTS public.account
(
    user_id integer NOT NULL DEFAULT nextval('user_user_id_seq'::regclass),
    name character varying(100) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    activation_token_hash text COLLATE pg_catalog."default",
    activation_expires_at timestamp without time zone,
    is_activated boolean NOT NULL DEFAULT false,
    CONSTRAINT user_pkey PRIMARY KEY (user_id),
    CONSTRAINT user_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.act_recitation
(
    act_recitation_id serial NOT NULL,
    class_id bigint,
    student_id integer,
    title character varying(255) COLLATE pg_catalog."default",
    score numeric(5, 2),
    date_created timestamp without time zone,
    grading_period character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Midterm'::character varying,
    CONSTRAINT act_recitation_pkey PRIMARY KEY (act_recitation_id)
);

CREATE TABLE IF NOT EXISTS public.act_submission
(
    act_submission_id serial NOT NULL,
    activity_id integer,
    student_id integer,
    file_path character varying(255) COLLATE pg_catalog."default",
    submission_date timestamp without time zone,
    score numeric(5, 2),
    submission_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Submitted'::character varying,
    feedback text COLLATE pg_catalog."default",
    graded_at timestamp without time zone,
    attempt_number integer NOT NULL DEFAULT 1,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    st_notes text COLLATE pg_catalog."default",
    grading_period character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Midterm'::character varying,
    CONSTRAINT act_submission_pkey PRIMARY KEY (act_submission_id)
);

CREATE TABLE IF NOT EXISTS public.activity
(
    activity_id serial NOT NULL,
    class_id bigint,
    title character varying(255) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    due_date timestamp without time zone,
    employee_id integer,
    file_path character varying(255) COLLATE pg_catalog."default",
    points integer,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Published'::character varying,
    publish_date timestamp without time zone,
    allow_late boolean NOT NULL DEFAULT false,
    max_attempts integer DEFAULT 1,
    visible_from timestamp without time zone,
    visible_until timestamp without time zone,
    grading_period character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Midterm'::character varying,
    topic_id bigint,
    content_level character varying(12) COLLATE pg_catalog."default" NOT NULL DEFAULT 'course'::character varying,
    content_key character varying(64) COLLATE pg_catalog."default",
    delivery_type character varying(12) COLLATE pg_catalog."default" NOT NULL DEFAULT 'online'::character varying,
    CONSTRAINT activity_pkey PRIMARY KEY (activity_id)
);

CREATE TABLE IF NOT EXISTS public.activity_sections
(
    id serial NOT NULL,
    activity_id integer,
    section_id integer,
    created_at date DEFAULT CURRENT_DATE,
    CONSTRAINT activity_sections_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ai_query
(
    query_id serial NOT NULL,
    user_id integer,
    query_text text COLLATE pg_catalog."default",
    response_text text COLLATE pg_catalog."default",
    "timestamp" timestamp without time zone,
    CONSTRAINT ai_query_pkey PRIMARY KEY (query_id)
);

CREATE TABLE IF NOT EXISTS public.announcement
(
    announcement_id bigserial NOT NULL,
    class_id bigint NOT NULL,
    employee_id integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Published'::character varying,
    publish_date date DEFAULT CURRENT_DATE,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT announcement_pkey PRIMARY KEY (announcement_id)
);

CREATE TABLE IF NOT EXISTS public.announcement_section
(
    announcement_id bigint NOT NULL,
    section_id integer NOT NULL,
    CONSTRAINT announcement_section_pkey PRIMARY KEY (announcement_id, section_id)
);

CREATE TABLE IF NOT EXISTS public.attendance
(
    attendance_id serial NOT NULL,
    class_id bigint,
    student_id integer,
    is_present boolean,
    score numeric(5, 2),
    date_created timestamp without time zone,
    grading_period character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Midterm'::character varying,
    CONSTRAINT attendance_pkey PRIMARY KEY (attendance_id)
);

CREATE TABLE IF NOT EXISTS public.attendance_mark
(
    session_id bigint NOT NULL,
    student_id integer NOT NULL,
    status character varying(10) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT attendance_mark_pkey PRIMARY KEY (session_id, student_id)
);

CREATE TABLE IF NOT EXISTS public.attendance_session
(
    session_id bigserial NOT NULL,
    class_id bigint NOT NULL,
    section_id integer NOT NULL,
    session_date date NOT NULL,
    grading_period character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_by integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT attendance_session_pkey PRIMARY KEY (session_id),
    CONSTRAINT attendance_session_class_id_section_id_session_date_key UNIQUE (class_id, section_id, session_date)
);

CREATE TABLE IF NOT EXISTS public.bug_report
(
    report_id bigserial NOT NULL,
    reporter_user_id integer,
    reporter_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    reporter_email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    reporter_role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    issue_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    subject character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'open'::character varying,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bug_report_pkey PRIMARY KEY (report_id)
);

CREATE TABLE IF NOT EXISTS public.class
(
    class_id bigserial NOT NULL,
    class_code character varying(10) COLLATE pg_catalog."default",
    employee_id integer,
    subject character varying(100) COLLATE pg_catalog."default",
    subject_id bigint,
    term_id bigint,
    workflow_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'legacy_review'::character varying,
    CONSTRAINT class_pkey PRIMARY KEY (class_id)
);

CREATE TABLE IF NOT EXISTS public.class_section
(
    class_id bigint NOT NULL,
    section_id integer NOT NULL,
    CONSTRAINT class_section_pkey PRIMARY KEY (class_id, section_id)
);

CREATE TABLE IF NOT EXISTS public.class_syllabus
(
    class_id bigint NOT NULL,
    file_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file_path character varying(255) COLLATE pg_catalog."default" NOT NULL,
    uploaded_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT class_syllabus_pkey PRIMARY KEY (class_id)
);

CREATE TABLE IF NOT EXISTS public.enrollment
(
    enrollment_id serial NOT NULL,
    student_id integer,
    class_id bigint,
    section_id integer,
    CONSTRAINT enrollment_pkey PRIMARY KEY (enrollment_id),
    CONSTRAINT enrollment_student_id_class_id_key UNIQUE (student_id, class_id)
);

CREATE TABLE IF NOT EXISTS public.enrollment_request
(
    request_id bigserial NOT NULL,
    section_id integer NOT NULL,
    student_id integer NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    requested_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decided_at timestamp without time zone,
    decided_by integer,
    CONSTRAINT enrollment_request_pkey PRIMARY KEY (request_id)
);

CREATE TABLE IF NOT EXISTS public.grade
(
    grade_id serial NOT NULL,
    student_id integer,
    class_id bigint,
    type character varying(20) COLLATE pg_catalog."default",
    score numeric(5, 2),
    total numeric(5, 2),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    grading_period character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT grade_pkey PRIMARY KEY (grade_id)
);

CREATE TABLE IF NOT EXISTS public.grade_publication
(
    class_id bigint NOT NULL,
    section_id integer NOT NULL,
    grading_period character varying(20) COLLATE pg_catalog."default" NOT NULL,
    syllabus_id bigint NOT NULL,
    snapshot jsonb NOT NULL,
    published_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_by integer NOT NULL,
    CONSTRAINT grade_publication_pkey PRIMARY KEY (class_id, section_id, grading_period)
);

CREATE TABLE IF NOT EXISTS public.grade_publication_history
(
    history_id bigserial NOT NULL,
    class_id bigint NOT NULL,
    section_id integer NOT NULL,
    grading_period character varying(20) COLLATE pg_catalog."default" NOT NULL,
    syllabus_id bigint NOT NULL,
    snapshot jsonb NOT NULL,
    published_at timestamp without time zone NOT NULL,
    published_by integer NOT NULL,
    archived_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT grade_publication_history_pkey PRIMARY KEY (history_id)
);

CREATE TABLE IF NOT EXISTS public.grade_visibility
(
    class_id bigint NOT NULL,
    section character varying(50) COLLATE pg_catalog."default" NOT NULL,
    grading_period character varying(20) COLLATE pg_catalog."default" NOT NULL,
    visible boolean NOT NULL DEFAULT false,
    CONSTRAINT grade_visibility_pkey PRIMARY KEY (class_id, section, grading_period)
);

CREATE TABLE IF NOT EXISTS public.grading_column
(
    column_id bigserial NOT NULL,
    class_id bigint NOT NULL,
    section character varying(50) COLLATE pg_catalog."default" NOT NULL,
    grading_period character varying(20) COLLATE pg_catalog."default" NOT NULL,
    category character varying(20) COLLATE pg_catalog."default" NOT NULL,
    label character varying(255) COLLATE pg_catalog."default" NOT NULL,
    total_items numeric(8, 2) NOT NULL,
    record_date date,
    teacher_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT grading_column_pkey PRIMARY KEY (column_id),
    CONSTRAINT grading_column_class_id_section_grading_period_category_lab_key UNIQUE (class_id, section, grading_period, category, label)
);

CREATE TABLE IF NOT EXISTS public.grading_policy
(
    policy_id serial NOT NULL,
    class_id bigint,
    attendance_weight numeric(5, 2),
    recit_weight numeric(5, 2),
    quizzes_weight numeric(5, 2),
    exam_weight numeric(5, 2),
    CONSTRAINT grading_policy_pkey PRIMARY KEY (policy_id),
    CONSTRAINT grading_policy_class_id_key UNIQUE (class_id)
);

CREATE TABLE IF NOT EXISTS public.grading_score
(
    score_id bigserial NOT NULL,
    column_id bigint NOT NULL,
    student_id integer NOT NULL,
    score numeric(8, 2),
    CONSTRAINT grading_score_pkey PRIMARY KEY (score_id),
    CONSTRAINT grading_score_column_id_student_id_key UNIQUE (column_id, student_id)
);

CREATE TABLE IF NOT EXISTS public.learning_content
(
    content_id bigserial NOT NULL,
    class_id bigint NOT NULL,
    topic_key character varying(64) COLLATE pg_catalog."default" NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    source_type character varying(12) COLLATE pg_catalog."default" NOT NULL,
    file_path character varying(512) COLLATE pg_catalog."default",
    extracted_text text COLLATE pg_catalog."default",
    edited_html text COLLATE pg_catalog."default",
    status character varying(12) COLLATE pg_catalog."default" NOT NULL DEFAULT 'draft'::character varying,
    created_by integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at timestamp without time zone,
    CONSTRAINT learning_content_pkey PRIMARY KEY (content_id)
);

CREATE TABLE IF NOT EXISTS public.learning_resource
(
    resource_id bigserial NOT NULL,
    class_id bigint NOT NULL,
    kind character varying(12) COLLATE pg_catalog."default" NOT NULL,
    content_level character varying(12) COLLATE pg_catalog."default" NOT NULL,
    content_key character varying(64) COLLATE pg_catalog."default" NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    body_html text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    extracted_text text COLLATE pg_catalog."default",
    url text COLLATE pg_catalog."default",
    file_path character varying(512) COLLATE pg_catalog."default",
    original_filename character varying(255) COLLATE pg_catalog."default",
    status character varying(12) COLLATE pg_catalog."default" NOT NULL DEFAULT 'draft'::character varying,
    display_order integer NOT NULL DEFAULT 0,
    legacy_module_id integer,
    created_by integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at timestamp without time zone,
    CONSTRAINT learning_resource_pkey PRIMARY KEY (resource_id),
    CONSTRAINT learning_resource_legacy_module_id_key UNIQUE (legacy_module_id)
);

CREATE TABLE IF NOT EXISTS public.legacy_review
(
    class_id bigint NOT NULL,
    reason text COLLATE pg_catalog."default" NOT NULL,
    resolved_at timestamp without time zone,
    CONSTRAINT legacy_review_pkey PRIMARY KEY (class_id)
);

CREATE TABLE IF NOT EXISTS public.module
(
    module_id serial NOT NULL,
    employee_id integer,
    title character varying(255) COLLATE pg_catalog."default",
    file_path character varying(255) COLLATE pg_catalog."default",
    upload_date timestamp without time zone,
    summary character varying(255) COLLATE pg_catalog."default",
    class_id integer,
    grading_period character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Midterm'::character varying,
    topic_id bigint,
    CONSTRAINT module_pkey PRIMARY KEY (module_id)
);

CREATE TABLE IF NOT EXISTS public.module_content
(
    text_id serial NOT NULL,
    module_id integer NOT NULL,
    text text COLLATE pg_catalog."default" NOT NULL,
    chunk_index integer NOT NULL,
    CONSTRAINT module_content_pkey PRIMARY KEY (text_id),
    CONSTRAINT module_content_module_chunk_key UNIQUE (module_id, chunk_index)
);

CREATE TABLE IF NOT EXISTS public.module_sections
(
    id serial NOT NULL,
    module_id integer,
    section_id integer,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT module_sections_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.query_context
(
    context_id serial NOT NULL,
    query_id integer,
    text_id integer,
    CONSTRAINT query_context_pkey PRIMARY KEY (context_id)
);

CREATE TABLE IF NOT EXISTS public.question
(
    question_id serial NOT NULL,
    quiz_id integer,
    question_text text COLLATE pg_catalog."default",
    correct_answer text COLLATE pg_catalog."default",
    question_type character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'short_answer'::character varying,
    choices jsonb,
    points numeric(8, 2) NOT NULL DEFAULT 1,
    display_order integer NOT NULL DEFAULT 0,
    explanation text COLLATE pg_catalog."default",
    CONSTRAINT question_pkey PRIMARY KEY (question_id)
);

CREATE TABLE IF NOT EXISTS public.quiz
(
    quiz_id serial NOT NULL,
    class_id bigint,
    title character varying(255) COLLATE pg_catalog."default",
    date_created timestamp without time zone,
    description text COLLATE pg_catalog."default",
    module_id integer,
    deadline timestamp without time zone,
    time_limit_minutes integer,
    total_points numeric(8, 2),
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Published'::character varying,
    max_attempts integer,
    topic_id bigint,
    grading_period character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Midterm'::character varying,
    delivery_type character varying(12) COLLATE pg_catalog."default" NOT NULL DEFAULT 'online'::character varying,
    origin character varying(12) COLLATE pg_catalog."default" NOT NULL DEFAULT 'manual'::character varying,
    content_level character varying(12) COLLATE pg_catalog."default" NOT NULL DEFAULT 'course'::character varying,
    content_key character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT quiz_pkey PRIMARY KEY (quiz_id)
);

CREATE TABLE IF NOT EXISTS public.quiz_score
(
    score_id serial NOT NULL,
    student_id integer,
    quiz_id integer,
    is_online boolean,
    total_score numeric(5, 2),
    date_taken timestamp without time zone,
    grading_period character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Midterm'::character varying,
    max_score numeric(8, 2),
    submitted_at timestamp without time zone DEFAULT now(),
    CONSTRAINT quiz_score_pkey PRIMARY KEY (score_id)
);

CREATE TABLE IF NOT EXISTS public.quiz_sections
(
    id serial NOT NULL,
    quiz_id integer NOT NULL,
    section_id integer NOT NULL,
    CONSTRAINT quiz_sections_pkey PRIMARY KEY (id),
    CONSTRAINT quiz_sections_quiz_id_section_id_key UNIQUE (quiz_id, section_id)
);

CREATE TABLE IF NOT EXISTS public.schema_migrations
(
    filename text COLLATE pg_catalog."default" NOT NULL,
    sha256 text COLLATE pg_catalog."default" NOT NULL,
    applied_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename)
);

CREATE TABLE IF NOT EXISTS public.section
(
    section_id serial NOT NULL,
    employee_id integer,
    section character varying(10) COLLATE pg_catalog."default",
    class_id integer,
    term_id bigint,
    year_level integer,
    adviser_id integer,
    join_code character varying(24) COLLATE pg_catalog."default",
    workflow_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'legacy_review'::character varying,
    CONSTRAINT section_pkey PRIMARY KEY (section_id)
);

CREATE TABLE IF NOT EXISTS public.section_member
(
    section_id integer NOT NULL,
    student_id integer NOT NULL,
    added_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT section_member_pkey PRIMARY KEY (section_id, student_id)
);

CREATE TABLE IF NOT EXISTS public.student
(
    student_id integer NOT NULL,
    user_id integer,
    CONSTRAINT student_pkey PRIMARY KEY (student_id),
    CONSTRAINT student_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.student_answer
(
    answer_id serial NOT NULL,
    student_id integer,
    quiz_id integer,
    answer_text text COLLATE pg_catalog."default",
    is_correct boolean,
    score_id integer,
    question_id integer,
    answer_json jsonb,
    answered_at timestamp without time zone DEFAULT now(),
    CONSTRAINT student_answer_pkey PRIMARY KEY (answer_id)
);

CREATE TABLE IF NOT EXISTS public.student_topic_progress
(
    topic_id bigint NOT NULL,
    student_id integer NOT NULL,
    completed boolean NOT NULL DEFAULT false,
    completed_at timestamp without time zone,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT student_topic_progress_pkey PRIMARY KEY (topic_id, student_id)
);

CREATE TABLE IF NOT EXISTS public.subject_catalog
(
    subject_id bigserial NOT NULL,
    code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    title character varying(150) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    units numeric(4, 1),
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT subject_catalog_pkey PRIMARY KEY (subject_id),
    CONSTRAINT subject_catalog_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.subject_enrollment_exception
(
    student_id integer NOT NULL,
    class_id bigint NOT NULL,
    action character varying(12) COLLATE pg_catalog."default" NOT NULL,
    teaching_section_id integer,
    reason text COLLATE pg_catalog."default",
    updated_by integer,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT subject_enrollment_exception_pkey PRIMARY KEY (student_id, class_id)
);

CREATE TABLE IF NOT EXISTS public.subject_enrollment_history
(
    history_id bigserial NOT NULL,
    student_id integer NOT NULL,
    class_id bigint NOT NULL,
    section_id integer,
    new_section_id integer,
    action character varying(20) COLLATE pg_catalog."default" NOT NULL,
    reason text COLLATE pg_catalog."default",
    changed_by integer,
    changed_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT subject_enrollment_history_pkey PRIMARY KEY (history_id)
);

CREATE TABLE IF NOT EXISTS public.syllabus_item_link
(
    class_id bigint NOT NULL,
    item_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    item_id integer NOT NULL,
    topic_key character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT syllabus_item_link_pkey PRIMARY KEY (class_id, item_type, item_id)
);

CREATE TABLE IF NOT EXISTS public.syllabus_section_override
(
    class_id bigint NOT NULL,
    section_id integer NOT NULL,
    item_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    item_id integer NOT NULL,
    visible boolean NOT NULL DEFAULT true,
    due_at timestamp without time zone,
    CONSTRAINT syllabus_section_override_pkey PRIMARY KEY (class_id, section_id, item_type, item_id)
);

CREATE TABLE IF NOT EXISTS public.syllabus_topic
(
    topic_id serial NOT NULL,
    class_id bigint NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    module_id integer,
    activity_id integer,
    quiz_id integer,
    sort_order integer NOT NULL DEFAULT 1,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    display_order integer NOT NULL DEFAULT 0,
    CONSTRAINT syllabus_topic_pkey PRIMARY KEY (topic_id)
);

CREATE TABLE IF NOT EXISTS public.syllabus_topic_progress
(
    student_id integer NOT NULL,
    topic_id integer NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'not_started'::character varying,
    progress_pct numeric(5, 2) NOT NULL DEFAULT 0,
    completed_at timestamp without time zone,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT syllabus_topic_progress_pkey PRIMARY KEY (student_id, topic_id)
);

CREATE TABLE IF NOT EXISTS public.syllabus_version
(
    syllabus_id bigserial NOT NULL,
    class_id bigint NOT NULL,
    version integer NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'draft'::character varying,
    source_name character varying(255) COLLATE pg_catalog."default",
    source_path character varying(255) COLLATE pg_catalog."default",
    content jsonb NOT NULL DEFAULT '{}'::jsonb,
    grading_rule jsonb NOT NULL DEFAULT '{}'::jsonb,
    import_warnings jsonb NOT NULL DEFAULT '[]'::jsonb,
    warnings_acknowledged boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at timestamp without time zone,
    CONSTRAINT syllabus_version_pkey PRIMARY KEY (syllabus_id),
    CONSTRAINT syllabus_version_class_id_version_key UNIQUE (class_id, version)
);

CREATE TABLE IF NOT EXISTS public.teacher
(
    employee_id serial NOT NULL,
    user_id integer,
    CONSTRAINT teacher_pkey PRIMARY KEY (employee_id),
    CONSTRAINT teacher_user_id_key UNIQUE (user_id)
);

ALTER TABLE IF EXISTS public.act_recitation
    ADD CONSTRAINT act_recitation_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.act_recitation
    ADD CONSTRAINT act_recitation_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.act_submission
    ADD CONSTRAINT act_submission_activity_id_fkey FOREIGN KEY (activity_id)
    REFERENCES public.activity (activity_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.act_submission
    ADD CONSTRAINT act_submission_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.activity
    ADD CONSTRAINT activity_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.activity
    ADD CONSTRAINT activity_employee_id_fkey FOREIGN KEY (employee_id)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.activity
    ADD CONSTRAINT activity_topic_id_fkey FOREIGN KEY (topic_id)
    REFERENCES public.syllabus_topic (topic_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.activity_sections
    ADD CONSTRAINT activity_sections_activity_id_fkey FOREIGN KEY (activity_id)
    REFERENCES public.activity (activity_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.activity_sections
    ADD CONSTRAINT activity_sections_section_id_fkey FOREIGN KEY (section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ai_query
    ADD CONSTRAINT ai_query_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.account (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.announcement
    ADD CONSTRAINT announcement_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.announcement
    ADD CONSTRAINT announcement_employee_id_fkey FOREIGN KEY (employee_id)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.announcement_section
    ADD CONSTRAINT announcement_section_announcement_id_fkey FOREIGN KEY (announcement_id)
    REFERENCES public.announcement (announcement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.announcement_section
    ADD CONSTRAINT announcement_section_section_id_fkey FOREIGN KEY (section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.attendance
    ADD CONSTRAINT attendance_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.attendance
    ADD CONSTRAINT attendance_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.attendance_mark
    ADD CONSTRAINT attendance_mark_session_id_fkey FOREIGN KEY (session_id)
    REFERENCES public.attendance_session (session_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.attendance_mark
    ADD CONSTRAINT attendance_mark_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.attendance_session
    ADD CONSTRAINT attendance_session_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.attendance_session
    ADD CONSTRAINT attendance_session_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.attendance_session
    ADD CONSTRAINT attendance_session_section_id_fkey FOREIGN KEY (section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bug_report
    ADD CONSTRAINT bug_report_reporter_user_id_fkey FOREIGN KEY (reporter_user_id)
    REFERENCES public.account (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.class
    ADD CONSTRAINT class_employee_id_fkey FOREIGN KEY (employee_id)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.class
    ADD CONSTRAINT class_subject_id_fkey FOREIGN KEY (subject_id)
    REFERENCES public.subject_catalog (subject_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.class
    ADD CONSTRAINT class_term_id_fkey FOREIGN KEY (term_id)
    REFERENCES public.academic_term (term_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.class_section
    ADD CONSTRAINT class_section_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.class_section
    ADD CONSTRAINT class_section_section_id_fkey FOREIGN KEY (section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.class_syllabus
    ADD CONSTRAINT class_syllabus_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS class_syllabus_pkey
    ON public.class_syllabus(class_id);


ALTER TABLE IF EXISTS public.enrollment
    ADD CONSTRAINT enrollment_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.enrollment
    ADD CONSTRAINT enrollment_section_id_fkey FOREIGN KEY (section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.enrollment
    ADD CONSTRAINT enrollment_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.enrollment_request
    ADD CONSTRAINT enrollment_request_decided_by_fkey FOREIGN KEY (decided_by)
    REFERENCES public.account (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.enrollment_request
    ADD CONSTRAINT enrollment_request_section_id_fkey FOREIGN KEY (section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.enrollment_request
    ADD CONSTRAINT enrollment_request_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grade
    ADD CONSTRAINT grade_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grade
    ADD CONSTRAINT grade_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grade_publication
    ADD CONSTRAINT grade_publication_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.grade_publication
    ADD CONSTRAINT grade_publication_published_by_fkey FOREIGN KEY (published_by)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grade_publication
    ADD CONSTRAINT grade_publication_section_id_fkey FOREIGN KEY (section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.grade_publication
    ADD CONSTRAINT grade_publication_syllabus_id_fkey FOREIGN KEY (syllabus_id)
    REFERENCES public.syllabus_version (syllabus_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grading_policy
    ADD CONSTRAINT grading_policy_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS grading_policy_class_id_key
    ON public.grading_policy(class_id);


ALTER TABLE IF EXISTS public.grading_score
    ADD CONSTRAINT grading_score_column_id_fkey FOREIGN KEY (column_id)
    REFERENCES public.grading_column (column_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.learning_content
    ADD CONSTRAINT learning_content_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.learning_content
    ADD CONSTRAINT learning_content_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.learning_resource
    ADD CONSTRAINT learning_resource_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.learning_resource
    ADD CONSTRAINT learning_resource_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.learning_resource
    ADD CONSTRAINT learning_resource_legacy_module_id_fkey FOREIGN KEY (legacy_module_id)
    REFERENCES public.module (module_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS learning_resource_legacy_module_id_key
    ON public.learning_resource(legacy_module_id);


ALTER TABLE IF EXISTS public.legacy_review
    ADD CONSTRAINT legacy_review_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS legacy_review_pkey
    ON public.legacy_review(class_id);


ALTER TABLE IF EXISTS public.module
    ADD CONSTRAINT module_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.module
    ADD CONSTRAINT module_employee_id_fkey FOREIGN KEY (employee_id)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.module
    ADD CONSTRAINT module_topic_id_fkey FOREIGN KEY (topic_id)
    REFERENCES public.syllabus_topic (topic_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.module_content
    ADD CONSTRAINT module_content_module_id_fkey FOREIGN KEY (module_id)
    REFERENCES public.module (module_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS module_content_module_id_idx
    ON public.module_content(module_id);


ALTER TABLE IF EXISTS public.module_sections
    ADD CONSTRAINT module_sections_module_id_fkey FOREIGN KEY (module_id)
    REFERENCES public.module (module_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.module_sections
    ADD CONSTRAINT module_sections_section_id_fkey FOREIGN KEY (section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.query_context
    ADD CONSTRAINT query_context_query_id_fkey FOREIGN KEY (query_id)
    REFERENCES public.ai_query (query_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.query_context
    ADD CONSTRAINT query_context_text_id_fkey FOREIGN KEY (text_id)
    REFERENCES public.module_content (text_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.question
    ADD CONSTRAINT question_quiz_id_fkey FOREIGN KEY (quiz_id)
    REFERENCES public.quiz (quiz_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quiz
    ADD CONSTRAINT quiz_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quiz
    ADD CONSTRAINT quiz_module_id_fkey FOREIGN KEY (module_id)
    REFERENCES public.module (module_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quiz
    ADD CONSTRAINT quiz_topic_id_fkey FOREIGN KEY (topic_id)
    REFERENCES public.syllabus_topic (topic_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.quiz_score
    ADD CONSTRAINT quiz_score_quiz_id_fkey FOREIGN KEY (quiz_id)
    REFERENCES public.quiz (quiz_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quiz_score
    ADD CONSTRAINT quiz_score_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quiz_sections
    ADD CONSTRAINT quiz_sections_quiz_id_fkey FOREIGN KEY (quiz_id)
    REFERENCES public.quiz (quiz_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.quiz_sections
    ADD CONSTRAINT quiz_sections_section_id_fkey FOREIGN KEY (section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.section
    ADD CONSTRAINT section_adviser_id_fkey FOREIGN KEY (adviser_id)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.section
    ADD CONSTRAINT section_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.section
    ADD CONSTRAINT section_employee_id_fkey FOREIGN KEY (employee_id)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.section
    ADD CONSTRAINT section_term_id_fkey FOREIGN KEY (term_id)
    REFERENCES public.academic_term (term_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.section_member
    ADD CONSTRAINT section_member_section_id_fkey FOREIGN KEY (section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.section_member
    ADD CONSTRAINT section_member_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.student
    ADD CONSTRAINT student_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.account (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS student_user_id_key
    ON public.student(user_id);


ALTER TABLE IF EXISTS public.student_answer
    ADD CONSTRAINT student_answer_question_id_fkey FOREIGN KEY (question_id)
    REFERENCES public.question (question_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student_answer
    ADD CONSTRAINT student_answer_quiz_id_fkey FOREIGN KEY (quiz_id)
    REFERENCES public.quiz (quiz_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student_answer
    ADD CONSTRAINT student_answer_score_id_fkey FOREIGN KEY (score_id)
    REFERENCES public.quiz_score (score_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student_answer
    ADD CONSTRAINT student_answer_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student_topic_progress
    ADD CONSTRAINT student_topic_progress_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.student_topic_progress
    ADD CONSTRAINT student_topic_progress_topic_id_fkey FOREIGN KEY (topic_id)
    REFERENCES public.syllabus_topic (topic_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.subject_enrollment_exception
    ADD CONSTRAINT subject_enrollment_exception_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.subject_enrollment_exception
    ADD CONSTRAINT subject_enrollment_exception_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.subject_enrollment_exception
    ADD CONSTRAINT subject_enrollment_exception_teaching_section_id_fkey FOREIGN KEY (teaching_section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.subject_enrollment_exception
    ADD CONSTRAINT subject_enrollment_exception_updated_by_fkey FOREIGN KEY (updated_by)
    REFERENCES public.account (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.subject_enrollment_history
    ADD CONSTRAINT subject_enrollment_history_changed_by_fkey FOREIGN KEY (changed_by)
    REFERENCES public.account (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.subject_enrollment_history
    ADD CONSTRAINT subject_enrollment_history_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.subject_enrollment_history
    ADD CONSTRAINT subject_enrollment_history_new_section_id_fkey FOREIGN KEY (new_section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.subject_enrollment_history
    ADD CONSTRAINT subject_enrollment_history_section_id_fkey FOREIGN KEY (section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.subject_enrollment_history
    ADD CONSTRAINT subject_enrollment_history_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.syllabus_item_link
    ADD CONSTRAINT syllabus_item_link_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.syllabus_section_override
    ADD CONSTRAINT syllabus_section_override_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.syllabus_section_override
    ADD CONSTRAINT syllabus_section_override_section_id_fkey FOREIGN KEY (section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.syllabus_topic
    ADD CONSTRAINT syllabus_topic_activity_id_fkey FOREIGN KEY (activity_id)
    REFERENCES public.activity (activity_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.syllabus_topic
    ADD CONSTRAINT syllabus_topic_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.syllabus_topic
    ADD CONSTRAINT syllabus_topic_module_id_fkey FOREIGN KEY (module_id)
    REFERENCES public.module (module_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.syllabus_topic
    ADD CONSTRAINT syllabus_topic_quiz_id_fkey FOREIGN KEY (quiz_id)
    REFERENCES public.quiz (quiz_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.syllabus_topic_progress
    ADD CONSTRAINT syllabus_topic_progress_topic_id_fkey FOREIGN KEY (topic_id)
    REFERENCES public.syllabus_topic (topic_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.syllabus_version
    ADD CONSTRAINT syllabus_version_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS syllabus_one_draft_idx
    ON public.syllabus_version(class_id);


ALTER TABLE IF EXISTS public.teacher
    ADD CONSTRAINT teacher_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.account (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS teacher_user_id_key
    ON public.teacher(user_id);

END;