-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.act_recitation
(
    act_recitation_id serial NOT NULL,
    class_id bigint,
    student_id integer,
    title character varying(255) COLLATE pg_catalog."default",
    score numeric(5, 2),
    date_created timestamp without time zone,
    CONSTRAINT act_recitation_pkey PRIMARY KEY (act_recitation_id)
);

CREATE TABLE IF NOT EXISTS public.act_submission
(
    act_submission_id serial NOT NULL,
    activity_id integer,
    student_id integer,
    file_path character varying(255) COLLATE pg_catalog."default",
    submission_date timestamp without time zone,
    score numeric(5, 2),
    submission_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Submitted'::character varying,
    feedback text COLLATE pg_catalog."default",
    graded_at timestamp without time zone,
    attempt_number integer NOT NULL DEFAULT 1,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT act_submission_pkey PRIMARY KEY (act_submission_id)
);

CREATE TABLE IF NOT EXISTS public.activity
(
    activity_id serial NOT NULL,
    class_id bigint,
    title character varying(255) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    due_date timestamp without time zone,
    employee_id integer,
    file_path character varying(255) COLLATE pg_catalog."default",
    points integer,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Published'::character varying,
    publish_date timestamp without time zone,
    allow_late boolean NOT NULL DEFAULT false,
    max_attempts integer DEFAULT 1,
    visible_from timestamp without time zone,
    visible_until timestamp without time zone,
    CONSTRAINT activity_pkey PRIMARY KEY (activity_id)
);

CREATE TABLE IF NOT EXISTS public.activity_sections
(
    id serial NOT NULL,
    activity_id integer,
    section_id integer,
    created_at date DEFAULT CURRENT_DATE,
    CONSTRAINT activity_sections_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ai_query
(
    query_id serial NOT NULL,
    user_id integer,
    query_text text COLLATE pg_catalog."default",
    response_text text COLLATE pg_catalog."default",
    "timestamp" timestamp without time zone,
    CONSTRAINT ai_query_pkey PRIMARY KEY (query_id)
);

CREATE TABLE IF NOT EXISTS public.announcement
(
    announcement_id bigserial NOT NULL,
    class_id bigint NOT NULL,
    employee_id integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Published'::character varying,
    publish_date date DEFAULT CURRENT_DATE,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT announcement_pkey PRIMARY KEY (announcement_id)
);

CREATE TABLE IF NOT EXISTS public.announcement_section
(
    announcement_id bigint NOT NULL,
    section_id integer NOT NULL,
    CONSTRAINT announcement_section_pkey PRIMARY KEY (announcement_id, section_id)
);

CREATE TABLE IF NOT EXISTS public.attendance
(
    attendance_id serial NOT NULL,
    class_id bigint,
    student_id integer,
    is_present boolean,
    score numeric(5, 2),
    date_created timestamp without time zone,
    CONSTRAINT attendance_pkey PRIMARY KEY (attendance_id)
);

CREATE TABLE IF NOT EXISTS public.class
(
    class_id bigserial NOT NULL,
    class_code character varying(10) COLLATE pg_catalog."default",
    employee_id integer,
    subject character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT class_pkey PRIMARY KEY (class_id)
);

CREATE TABLE IF NOT EXISTS public.enrollment
(
    enrollment_id serial NOT NULL,
    student_id integer,
    class_id bigint,
    CONSTRAINT enrollment_pkey PRIMARY KEY (enrollment_id),
    CONSTRAINT enrollment_student_id_class_id_key UNIQUE (student_id, class_id)
);

CREATE TABLE IF NOT EXISTS public.grade
(
    grade_id serial NOT NULL,
    student_id integer,
    class_id bigint,
    type character varying(20) COLLATE pg_catalog."default",
    score numeric(5, 2),
    total numeric(5, 2),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT grade_pkey PRIMARY KEY (grade_id)
);

CREATE TABLE IF NOT EXISTS public.grading_policy
(
    policy_id serial NOT NULL,
    class_id bigint,
    attendance_weight numeric(5, 2),
    recit_weight numeric(5, 2),
    quizzes_weight numeric(5, 2),
    exam_weight numeric(5, 2),
    CONSTRAINT grading_policy_pkey PRIMARY KEY (policy_id),
    CONSTRAINT grading_policy_class_id_key UNIQUE (class_id)
);

CREATE TABLE IF NOT EXISTS public.module
(
    module_id serial NOT NULL,
    employee_id integer,
    title character varying(255) COLLATE pg_catalog."default",
    file_path character varying(255) COLLATE pg_catalog."default",
    upload_date timestamp without time zone,
    summary character varying(255) COLLATE pg_catalog."default",
    class_id integer,
    CONSTRAINT module_pkey PRIMARY KEY (module_id)
);

CREATE TABLE IF NOT EXISTS public.module_content
(
    text_id serial NOT NULL,
    module_id integer,
    text text COLLATE pg_catalog."default",
    chunk_index integer,
    CONSTRAINT module_content_pkey PRIMARY KEY (text_id)
);

CREATE TABLE IF NOT EXISTS public.module_sections
(
    id serial NOT NULL,
    module_id integer,
    section_id integer,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT module_sections_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.query_context
(
    context_id serial NOT NULL,
    query_id integer,
    text_id integer,
    CONSTRAINT query_context_pkey PRIMARY KEY (context_id)
);

CREATE TABLE IF NOT EXISTS public.question
(
    question_id serial NOT NULL,
    quiz_id integer,
    question_text text COLLATE pg_catalog."default",
    correct_answer text COLLATE pg_catalog."default",
    CONSTRAINT question_pkey PRIMARY KEY (question_id)
);

CREATE TABLE IF NOT EXISTS public.quiz
(
    quiz_id serial NOT NULL,
    class_id bigint,
    title character varying(255) COLLATE pg_catalog."default",
    date_created timestamp without time zone,
    CONSTRAINT quiz_pkey PRIMARY KEY (quiz_id)
);

CREATE TABLE IF NOT EXISTS public.quiz_score
(
    score_id serial NOT NULL,
    student_id integer,
    quiz_id integer,
    is_online boolean,
    total_score numeric(5, 2),
    date_taken timestamp without time zone,
    CONSTRAINT quiz_score_pkey PRIMARY KEY (score_id)
);

CREATE TABLE IF NOT EXISTS public.section
(
    section_id serial NOT NULL,
    employee_id integer,
    section character varying(10) COLLATE pg_catalog."default",
    class_id integer,
    CONSTRAINT section_pkey PRIMARY KEY (section_id)
);

CREATE TABLE IF NOT EXISTS public.student
(
    student_id integer NOT NULL,
    user_id integer,
    CONSTRAINT student_pkey PRIMARY KEY (student_id),
    CONSTRAINT student_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.student_answer
(
    answer_id serial NOT NULL,
    student_id integer,
    quiz_id integer,
    answer_text text COLLATE pg_catalog."default",
    is_correct boolean,
    CONSTRAINT student_answer_pkey PRIMARY KEY (answer_id)
);

CREATE TABLE IF NOT EXISTS public.teacher
(
    employee_id serial NOT NULL,
    user_id integer,
    CONSTRAINT teacher_pkey PRIMARY KEY (employee_id),
    CONSTRAINT teacher_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    user_id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    username character varying(100) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_pkey PRIMARY KEY (user_id),
    CONSTRAINT user_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.act_recitation
    ADD CONSTRAINT act_recitation_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.act_recitation
    ADD CONSTRAINT act_recitation_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.act_submission
    ADD CONSTRAINT act_submission_activity_id_fkey FOREIGN KEY (activity_id)
    REFERENCES public.activity (activity_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.act_submission
    ADD CONSTRAINT act_submission_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.activity
    ADD CONSTRAINT activity_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.activity
    ADD CONSTRAINT activity_employee_id_fkey FOREIGN KEY (employee_id)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.activity_sections
    ADD CONSTRAINT activity_sections_activity_id_fkey FOREIGN KEY (activity_id)
    REFERENCES public.activity (activity_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.activity_sections
    ADD CONSTRAINT activity_sections_section_id_fkey FOREIGN KEY (section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ai_query
    ADD CONSTRAINT ai_query_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.announcement
    ADD CONSTRAINT announcement_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.announcement
    ADD CONSTRAINT announcement_employee_id_fkey FOREIGN KEY (employee_id)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.announcement_section
    ADD CONSTRAINT announcement_section_announcement_id_fkey FOREIGN KEY (announcement_id)
    REFERENCES public.announcement (announcement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.announcement_section
    ADD CONSTRAINT announcement_section_section_id_fkey FOREIGN KEY (section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.attendance
    ADD CONSTRAINT attendance_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.attendance
    ADD CONSTRAINT attendance_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.class
    ADD CONSTRAINT class_employee_id_fkey FOREIGN KEY (employee_id)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.enrollment
    ADD CONSTRAINT enrollment_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.enrollment
    ADD CONSTRAINT enrollment_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grade
    ADD CONSTRAINT grade_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grade
    ADD CONSTRAINT grade_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grading_policy
    ADD CONSTRAINT grading_policy_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS grading_policy_class_id_key
    ON public.grading_policy(class_id);


ALTER TABLE IF EXISTS public.module
    ADD CONSTRAINT module_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.module
    ADD CONSTRAINT module_employee_id_fkey FOREIGN KEY (employee_id)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.module_content
    ADD CONSTRAINT module_content_module_id_fkey FOREIGN KEY (module_id)
    REFERENCES public.module (module_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.module_sections
    ADD CONSTRAINT module_sections_module_id_fkey FOREIGN KEY (module_id)
    REFERENCES public.module (module_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.module_sections
    ADD CONSTRAINT module_sections_section_id_fkey FOREIGN KEY (section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.query_context
    ADD CONSTRAINT query_context_query_id_fkey FOREIGN KEY (query_id)
    REFERENCES public.ai_query (query_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.query_context
    ADD CONSTRAINT query_context_text_id_fkey FOREIGN KEY (text_id)
    REFERENCES public.module_content (text_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.question
    ADD CONSTRAINT question_quiz_id_fkey FOREIGN KEY (quiz_id)
    REFERENCES public.quiz (quiz_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quiz
    ADD CONSTRAINT quiz_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quiz_score
    ADD CONSTRAINT quiz_score_quiz_id_fkey FOREIGN KEY (quiz_id)
    REFERENCES public.quiz (quiz_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quiz_score
    ADD CONSTRAINT quiz_score_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.section
    ADD CONSTRAINT section_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.section
    ADD CONSTRAINT section_employee_id_fkey FOREIGN KEY (employee_id)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student
    ADD CONSTRAINT student_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS student_user_id_key
    ON public.student(user_id);


ALTER TABLE IF EXISTS public.student_answer
    ADD CONSTRAINT student_answer_quiz_id_fkey FOREIGN KEY (quiz_id)
    REFERENCES public.quiz (quiz_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student_answer
    ADD CONSTRAINT student_answer_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.teacher
    ADD CONSTRAINT teacher_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS teacher_user_id_key
    ON public.teacher(user_id);

END;