-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.user
(
    user_id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    username character varying(100) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "user_pkey" PRIMARY KEY (user_id),
    CONSTRAINT "user_email_key" UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.act_recitation
(
    act_recitation_id serial NOT NULL,
    class_id varchar(5),
    student_id integer,
    title character varying(255) COLLATE pg_catalog."default",
    score numeric(5, 2),
    date_created timestamp without time zone,
    CONSTRAINT act_recitation_pkey PRIMARY KEY (act_recitation_id)
);

CREATE TABLE IF NOT EXISTS public.act_submission
(
    act_submission_id serial NOT NULL,
    activity_id integer,
    student_id integer,
    file_path character varying(255) COLLATE pg_catalog."default",
    submission_date timestamp without time zone,
    score numeric(5, 2),
    CONSTRAINT act_submission_pkey PRIMARY KEY (act_submission_id)
);

CREATE TABLE IF NOT EXISTS public.activity
(
    activity_id serial NOT NULL,
    class_id varchar(5),
    title character varying(255) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    due_date timestamp without time zone,
    employee_id integer,
    CONSTRAINT activity_pkey PRIMARY KEY (activity_id)
);

CREATE TABLE IF NOT EXISTS public.activity_grade
(
    activity_grade_id serial NOT NULL,
    class_id varchar(5),
    student_id integer,
    activity_grade_total numeric(5, 2),
    activity_grd numeric(5, 2),
    activity_grade_computed boolean,
    CONSTRAINT activity_grade_pkey PRIMARY KEY (activity_grade_id)
);

CREATE TABLE IF NOT EXISTS public.ai_query
(
    query_id serial NOT NULL,
    user_id integer,
    query_text text COLLATE pg_catalog."default",
    response_text text COLLATE pg_catalog."default",
    "timestamp" timestamp without time zone,
    CONSTRAINT ai_query_pkey PRIMARY KEY (query_id)
);

CREATE TABLE IF NOT EXISTS public.attendance
(
    attendance_id serial NOT NULL,
    class_id varchar(5),
    student_id integer,
    is_present boolean,
    score numeric(5, 2),
    date_created timestamp without time zone,
    CONSTRAINT attendance_pkey PRIMARY KEY (attendance_id)
);

CREATE TABLE IF NOT EXISTS public.attendance_grade
(
    attendance_grade_id serial NOT NULL,
    class_id varchar(5),
    student_id integer,
    attendance_total numeric(5, 2),
    attendance_grd numeric(5, 2),
    attendance_computed boolean,
    CONSTRAINT attendance_grade_pkey PRIMARY KEY (attendance_grade_id)
);

CREATE TABLE IF NOT EXISTS public.class
(
    class_id varchar(5) NOT NULL,
    employee_id integer,
    section_id integer,
    subject character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT class_pkey PRIMARY KEY (class_id)
);

CREATE TABLE IF NOT EXISTS public.enrollment
(
    enrollment_id serial NOT NULL,
    student_id integer,
    class_id varchar(5),
    CONSTRAINT enrollment_pkey PRIMARY KEY (enrollment_id)
);

CREATE TABLE IF NOT EXISTS public.grade
(
    grade_id serial NOT NULL,
    class_id varchar(5),
    student_id integer,
    attendance_grade_id integer,
    activity_grade_id integer,
    quiz_grade_id integer,
    p_grd numeric(5, 2),
    remark character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT grade_pkey PRIMARY KEY (grade_id)
);

CREATE TABLE IF NOT EXISTS public.grading_policy
(
    policy_id serial NOT NULL,
    class_id varchar(5),
    attendance_weight numeric(5, 2),
    recit_weight numeric(5, 2),
    quizzes_weight numeric(5, 2),
    exam_weight numeric(5, 2),
    CONSTRAINT grading_policy_pkey PRIMARY KEY (policy_id),
    CONSTRAINT grading_policy_class_id_key UNIQUE (class_id)
);

CREATE TABLE IF NOT EXISTS public.module
(
    module_id serial NOT NULL,
    class_id varchar(5),
    user_id integer,
    title character varying(255) COLLATE pg_catalog."default",
    file_path character varying(255) COLLATE pg_catalog."default",
    upload_date timestamp without time zone,
    CONSTRAINT module_pkey PRIMARY KEY (module_id)
);

CREATE TABLE IF NOT EXISTS public.module_content
(
    text_id serial NOT NULL,
    module_id integer,
    text text COLLATE pg_catalog."default",
    chunk_index integer,
    CONSTRAINT module_content_pkey PRIMARY KEY (text_id)
);

CREATE TABLE IF NOT EXISTS public.query_context
(
    context_id serial NOT NULL,
    query_id integer,
    text_id integer,
    CONSTRAINT query_context_pkey PRIMARY KEY (context_id)
);

CREATE TABLE IF NOT EXISTS public.question
(
    question_id serial NOT NULL,
    quiz_id integer,
    question_text text COLLATE pg_catalog."default",
    correct_answer text COLLATE pg_catalog."default",
    CONSTRAINT question_pkey PRIMARY KEY (question_id)
);

CREATE TABLE IF NOT EXISTS public.quiz
(
    quiz_id serial NOT NULL,
    class_id varchar(5),
    title character varying(255) COLLATE pg_catalog."default",
    date_created timestamp without time zone,
    CONSTRAINT quiz_pkey PRIMARY KEY (quiz_id)
);

CREATE TABLE IF NOT EXISTS public.quiz_grade
(
    quiz_grade_id serial NOT NULL,
    class_id varchar(5),
    student_id integer,
    quiz_grade_total numeric(5, 2),
    quiz_grd numeric(5, 2),
    quiz_grade_computed boolean,
    CONSTRAINT quiz_grade_pkey PRIMARY KEY (quiz_grade_id)
);

CREATE TABLE IF NOT EXISTS public.quiz_score
(
    score_id serial NOT NULL,
    student_id integer,
    quiz_id integer,
    is_online boolean,
    total_score numeric(5, 2),
    date_taken timestamp without time zone,
    CONSTRAINT quiz_score_pkey PRIMARY KEY (score_id)
);

CREATE TABLE IF NOT EXISTS public.section
(
    section_id serial NOT NULL,
    employee_id integer,
    section character varying(3) COLLATE pg_catalog."default",
    CONSTRAINT section_pkey PRIMARY KEY (section_id)
);

CREATE TABLE IF NOT EXISTS public.student
(
    student_id integer NOT NULL,
    user_id integer,
    CONSTRAINT student_pkey PRIMARY KEY (student_id),
    CONSTRAINT student_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.student_answer
(
    answer_id serial NOT NULL,
    student_id integer,
    quiz_id integer,
    answer_text text COLLATE pg_catalog."default",
    is_correct boolean,
    CONSTRAINT student_answer_pkey PRIMARY KEY (answer_id)
);

CREATE TABLE IF NOT EXISTS public.teacher
(
    employee_id serial NOT NULL,
    user_id integer,
    CONSTRAINT teacher_pkey PRIMARY KEY (employee_id),
    CONSTRAINT teacher_user_id_key UNIQUE (user_id)
);

ALTER TABLE IF EXISTS public.act_recitation
    ADD CONSTRAINT act_recitation_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.act_recitation
    ADD CONSTRAINT act_recitation_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.act_submission
    ADD CONSTRAINT act_submission_activity_id_fkey FOREIGN KEY (activity_id)
    REFERENCES public.activity (activity_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.act_submission
    ADD CONSTRAINT act_submission_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.activity
    ADD CONSTRAINT activity_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.activity
    ADD CONSTRAINT activity_employee_id_fkey FOREIGN KEY (employee_id)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.activity_grade
    ADD CONSTRAINT activity_grade_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.activity_grade
    ADD CONSTRAINT activity_grade_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ai_query
    ADD CONSTRAINT ai_query_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.attendance
    ADD CONSTRAINT attendance_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.attendance
    ADD CONSTRAINT attendance_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.attendance_grade
    ADD CONSTRAINT attendance_grade_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.attendance_grade
    ADD CONSTRAINT attendance_grade_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.class
    ADD CONSTRAINT class_employee_id_fkey FOREIGN KEY (employee_id)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.class
    ADD CONSTRAINT class_section_id_fkey FOREIGN KEY (section_id)
    REFERENCES public.section (section_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.enrollment
    ADD CONSTRAINT enrollment_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.enrollment
    ADD CONSTRAINT enrollment_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grade
    ADD CONSTRAINT grade_activity_grade_id_fkey FOREIGN KEY (activity_grade_id)
    REFERENCES public.activity_grade (activity_grade_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grade
    ADD CONSTRAINT grade_attendance_grade_id_fkey FOREIGN KEY (attendance_grade_id)
    REFERENCES public.attendance_grade (attendance_grade_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grade
    ADD CONSTRAINT grade_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grade
    ADD CONSTRAINT grade_quiz_grade_id_fkey FOREIGN KEY (quiz_grade_id)
    REFERENCES public.quiz_grade (quiz_grade_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grade
    ADD CONSTRAINT grade_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grading_policy
    ADD CONSTRAINT grading_policy_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS grading_policy_class_id_key
    ON public.grading_policy(class_id);


ALTER TABLE IF EXISTS public.module
    ADD CONSTRAINT module_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.module
    ADD CONSTRAINT module_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.module_content
    ADD CONSTRAINT module_content_module_id_fkey FOREIGN KEY (module_id)
    REFERENCES public.module (module_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.query_context
    ADD CONSTRAINT query_context_query_id_fkey FOREIGN KEY (query_id)
    REFERENCES public.ai_query (query_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.query_context
    ADD CONSTRAINT query_context_text_id_fkey FOREIGN KEY (text_id)
    REFERENCES public.module_content (text_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.question
    ADD CONSTRAINT question_quiz_id_fkey FOREIGN KEY (quiz_id)
    REFERENCES public.quiz (quiz_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quiz
    ADD CONSTRAINT quiz_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quiz_grade
    ADD CONSTRAINT quiz_grade_class_id_fkey FOREIGN KEY (class_id)
    REFERENCES public.class (class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quiz_grade
    ADD CONSTRAINT quiz_grade_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quiz_score
    ADD CONSTRAINT quiz_score_quiz_id_fkey FOREIGN KEY (quiz_id)
    REFERENCES public.quiz (quiz_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quiz_score
    ADD CONSTRAINT quiz_score_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.section
    ADD CONSTRAINT section_employee_id_fkey FOREIGN KEY (employee_id)
    REFERENCES public.teacher (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student
    ADD CONSTRAINT student_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS student_user_id_key
    ON public.student(user_id);


ALTER TABLE IF EXISTS public.student_answer
    ADD CONSTRAINT student_answer_quiz_id_fkey FOREIGN KEY (quiz_id)
    REFERENCES public.quiz (quiz_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student_answer
    ADD CONSTRAINT student_answer_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.teacher
    ADD CONSTRAINT teacher_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS teacher_user_id_key
    ON public.teacher(user_id);

END;